Update AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
Juanfrank/AA_CombatExtendedPatch pull request #65
Opened 2020-04-22 18:26 UTC by Breadbox2k19

2020-04-22 23:49 UTC, Juanfrank requested changes

2020-04-22 23:49 UTC, Juanfrank commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +								<li>BiteBlunt</li>
CE only accepts bite, cut, blunt and poke afaik. Changing the capacity to something else might break it. If you wanna have both you have to do 
<li>Bite</li>
<li>Blunt</li>

Either way the mechanic of bite includes a blunt and sharp component so it's redundant.

2020-04-23 04:38 UTC, Breadbox2k19 commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +								<li>BiteBlunt</li>
Biteblunt is a legit damage capacity accepted by CE, alot of vanilla animals in CE are patched with this. Biteblunt is simply blunt damage with a different label, it different from sharp damage with blunt penetration.

2020-04-23 19:03 UTC, Juanfrank commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +							<chanceFactor>1</chanceFactor>
What does this node do?

2020-04-23 19:07 UTC, Breadbox2k19 commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +							<chanceFactor>1</chanceFactor>
Chance factor affects how likely the attack is chosen.

2020-04-23 19:10 UTC, Juanfrank commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +							<chanceFactor>1</chanceFactor>
1 is 100% right so it would use it every single time

2020-04-24 13:58 UTC, Breadbox2k19 commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +							<chanceFactor>1</chanceFactor>
No I don’t think it works like that, it just means it works as per normal as if it is mot there.

2020-04-24 14:01 UTC, Juanfrank commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml
> +							<chanceFactor>1</chanceFactor>
Then I'll just remove it since it's extra code

2020-04-24 14:02 UTC, merged