Update AlphaAnimals_CE_Patch_Race_Goliath.xml
Juanfrank/AA_CombatExtendedPatch pull request #8
Opened 2020-04-16 16:10 UTC by Breadbox2k19

Machine man punch hard.
Health patched to be similar to Centipede.

2020-04-16 23:05 UTC, Juanfrank requested changes
75% crit chance with 28 power will probably rip kill an SM7-Android in 3 hits damn.

2020-04-16 23:05 UTC, Juanfrank commented on Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Goliath.xml
> +					<MeleeCritChance>0.75</MeleeCritChance>
Woah hold your horses, or I'm gonna give him some power gauntlets

2020-04-17 01:26 UTC, Juanfrank approved these changes

2020-04-17 01:29 UTC, merged

2020-04-17 06:11 UTC, Breadbox2k19 commented
You have to understand that crit chance does not result in extra damage, crit for blunt weapons means a temporary stun, crits by animals=a short knockdown, crit by sharp damage=bypass armour.

Also centipedes does 36 damage per melee attack so it’s actually doesn’t hit as hard as a Cent in melee. Every stats I make is made with reference to others.